/**
 * Data Loader
 * Utility for accessing normalized data through Vite's JSON import
 * This approach allows data to be statically loaded at build time
 */

// Import normalized JSON files
// These files are generated by the sync scripts in data/normalized/
import teamsData from '../../data/normalized/teams.json';
import playersData from '../../data/normalized/players.json';
import gameweeksData from '../../data/normalized/gameweeks.json';
import elementTypesData from '../../data/normalized/element-types.json';

export interface DataFiles {
  teams: unknown;
  players: unknown;
  gameweeks: unknown;
  elementTypes: unknown;
}

export function getDataFiles(): DataFiles {
  return {
    teams: teamsData,
    players: playersData,
    gameweeks: gameweeksData,
    elementTypes: elementTypesData,
  };
}
