export const DECISION_HUB_CONFIG = {
  FORM: {
    WINDOWS: [3, 5, 8] as const,
    EXCELLENT_THRESHOLD: 6.8,
    GOOD_THRESHOLD: 5.6,
    AVERAGE_THRESHOLD: 4.5,
  },
  CAPTAIN: {
    MIN_MINUTES: 500,
    MAX_RESULTS: 12,
    FORM_WEIGHT: 0.24,
    FIXTURE_WEIGHT: 0.2,
    HOME_AWAY_WEIGHT: 0.06,
    RELIABILITY_WEIGHT: 0.14,
    INVOLVEMENT_WEIGHT: 0.16,
    PENALTY_WEIGHT: 0.07,
    SET_PIECE_WEIGHT: 0.05,
    OWNERSHIP_WEIGHT: 0.04,
    DIFFERENTIAL_WEIGHT: 0.04,
    SCORE_MULTIPLIER: 100,
  },
  TRANSFERS: {
    BUY_THRESHOLD: 66,
    WATCHLIST_THRESHOLD: 52,
    SELL_THRESHOLD: 38,
    MIN_MINUTES: 500,
    MAX_RESULTS: 20,
  },
  FIXTURE_RUNS: {
    SHORT_HORIZON: 3,
    MEDIUM_HORIZON: 5,
    LONG_HORIZON: 8,
    MAX_TEAMS: 20,
  },
  DIFFERENTIALS: {
    MAX_OWNERSHIP: 15,
    MIN_FORM_SCORE: 5,
    MIN_MINUTES: 600,
    LIMIT: 20,
  },
  VALUE_INDEX: {
    LIMIT: 30,
  },
  TEAM_INSIGHTS: {
    HIGH_RISK_FIXTURE_FDR: 3.8,
    LOW_MINUTES_THRESHOLD: 600,
  },
} as const;
