export const DECISION_HUB_CONFIG = {
  CAPTAIN: {
    MIN_MINUTES: 500,
    MAX_RESULTS: 12,
    FORM_WEIGHT: 0.4,
    FIXTURE_WEIGHT: 0.35,
    RELIABILITY_WEIGHT: 0.25,
  },
  TRANSFERS: {
    MIN_TRANSFER_SCORE: 6,
    MIN_MINUTES: 500,
    MAX_RESULTS: 20,
  },
  FIXTURE_RUNS: {
    HORIZON: 5,
    MAX_TEAMS: 20,
  },
  TEAM_INSIGHTS: {
    HIGH_RISK_FIXTURE_FDR: 3.8,
    LOW_MINUTES_THRESHOLD: 600,
  },
} as const;
